dist: bionic

language: minimal

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
# thank you https://stackoverflow.com/a/47441734
# this is requried to be able to checkout branches after fetching
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch origin deployment
- pip3 install --user jinja2;
- sudo add-apt-repository -y ppa:mhier/libboost-latest
- sudo apt install -y libboost1.70-dev

script:
- tools/travis-ci-script.sh || travis_terminate 1
